---
title: "Replication of Study by Lopez-Brau & Jara-Ettinger (2023, Cognition)"
author: "Anushka Laha (anlaha@ucsd.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  pdf:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

[No abstract is needed.]  Each replication project will have a straightforward, no frills report of the study and results.  These reports will be publicly available as supplementary material for the aggregate report(s) of the project as a whole.  Also, to maximize project integrity, the intro and methods will be written and critiqued in advance of data collection.  Introductions can be just 1-2 paragraphs clarifying the main idea of the original study, the target finding for replication, and any other essential information. You will likely contact the authors of the original study, so this should be professional and forward facing. It will NOT have a literature review -- that is in the original publication. You can write both the introduction and the methods in past tense.  
  I'm aiming to replicate the results from Experiment 2 of the Lopez-Brau & Ettinger (2023) paper. The paper broadly revolves around the inferences humans make about the social meaning of objects, specifically investigating whether adults are able to infer the communicative meaning of objects from their placement. This experiment finds that adults believe that objects that impose a low cost on deciders are more likely to be communicative relative to objects that do not impose a cost. I anticipate leading projects on similar questions to investigate what inferences children make about the social meaning of objects. Replicating the methods and analysis will therefore be beneficial, serving as background findings motivating my studies and as a first step to brainstorming potential project designs and analysis plans for my own studies.  
  
  The stimuli will consist of eight sets of images. Each set will have a pair of doors side-by-side: one “low-cost door” (object placed in front of the door) and one “no-cost door” (object placed beside the door). The objects will be a plant, a chair, a pile of books, a pile of cinderblocks, some tape, some meter sticks, a hat, and a fishbowl tied to a tack on a door frame. Participants will be asked to imagine leaving an office and encountering this pair of doors. They will be asked a series of multiple-choice questions: an attention-check (“What objects are in front of the doors?”), test trial (“Which door do you think someone was trying to tell you something?”), a manipulation check (“Which door requires more work to walk through?”) and lastly, an inclusion question (“Do you think you would be able to walk through this door if you wanted to?”). 
  I anticipate the main challenges to be setting up the paradigm, specifically programming it using JavaScript which is unfamiliar to me. I imagine that it might be further challenging to code the study design such that failure on the attention checks reroutes participants to the start of the story and does not allow them to continue with the experiment until they pass the check (as per the published study design). I also look forward to learning how to collect data on the SONA platform, since the process is new to me. Gaining skills in carrying out a jsPsych experiment and collecting data on SONA may both be helpful in the case I need to run or pilot studies on adult samples.
  
Link to my repository: https://github.com/anlaha/lopez-brau2023; Original Paper hosted on repository at: https://github.com/anlaha/lopez-brau2023/tree/main/original_paper 

## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
